name: deepsky_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  auto_size_text: ^3.0.0
  dynamic_color: ^1.6.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.2
  flutter_svg: ^2.0.4
  freezed_annotation: ^2.2.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2

flutter:
  uses-material-design: true

  fonts:
    - family: Noto Sans JP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.otf

  assets:
    - assets/svg/